export const subjects = {
  'A': 'Vedas',
  'A1': 'Vedas, Rig Veda',
  'A2': 'Vedas, Yajur Veda',
  'A3': 'Vedas, Sama Veda',
  'A4': 'Vedas, Atharvana Veda',
  'A5': 'Vedas, Smriti and Sutra Literature',
  'A6': 'Vedas, Miscellaneous',
  'B': 'Vedangas',
  'B1': 'Vedangas, Kalpa',
  'B2': 'Vedangas, Chandas',
  'B3': 'Vedangas, Jyotisha',
  'B4': 'Vedangas, Siksha',
  'B5': 'Vedangas, Nirukta',
  'B6': 'Vedangas, Vyakarana',
  'B7': 'Vedangas, Micellaneous',
  'C': 'Sastras',
  'C1': 'Sastras, Vaiseshika',
  'C2': 'Sastras, Nyaya',
  'C3': 'Sastras, Sankhya',
  'C4': 'Sastras, Yoga',
  'C5': 'Sastras, Mimamsa',
  'C6': 'Sastras, Vedanta',
  'C7': 'Sastras, Avaidika Darshanas',
  'C8': 'Sastras, Other Sastras',
  'C9': 'Sastras, Miscellaneous',
  'D': 'Itihasa',
  'D1': 'Itihasa, Ramayana',
  'D2': 'Itihasa, Mahabharata',
  'D3': 'Itihasa, Other Languages',
  'D4': 'Itihasa, Miscellaneous',
  'E': 'Puranas',
  'F': 'Poetry',
  'F1': 'Poetry, Major',
  'F2': 'Poetry, Lyrics and Minor Poems',
  'G': 'Prose',
  'H': 'Champu',
  'I': 'Drama',
  'I1': 'Drama, Dance Music and Dramaturgy',
  'J': 'Alankara Sastra',
  'J1': 'Alankara Sastra, Miscellaneous',
  'K': 'History of Literature',
  'L': 'Linguistics and Philology',
  'M': 'Miscellaneous',
  'M1': 'Miscellaneous, Biographies and Contributions',
  'N': 'Ramakrishna and Vivekananda Literatures',
  'O': 'Textbooks',
  'P': 'Journal and Felicitation Volumes',
  'R': 'Research and Reference Books',
  'S': 'Tales and Fables'
};
